# -*- coding: utf-8 -*-
"""Style_Gan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9khyZAPUJF2nDrMzCuf5Qz3oGY08_ul
"""

# @title 🚀 DAY 2: RESUME TRAINING (Automated)
import os
import glob
import shutil
from google.colab import drive

# 1. Mount Drive & Re-install Engine (Required every new session)
print("✅ Mounting Drive...")
drive.mount('/content/drive')

print("⬇️ Re-installing StyleGAN2 (Colab wipes this daily)...")
if os.path.exists('/content/stylegan2-ada-pytorch'):
    shutil.rmtree('/content/stylegan2-ada-pytorch')

# Install the STABLE version
!git clone https://github.com/dvschultz/stylegan2-ada-pytorch /content/stylegan2-ada-pytorch
# Standard pip install is faster for Day 2
!pip install ninja opensimplex torch==1.13.1+cu116 torchvision==0.14.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 > /dev/null 2>&1

# Apply the "Red Text" Silencer Patch again just in case
print("🔧 Silencing C++ warnings...")
ops_file = '/content/stylegan2-ada-pytorch/torch_utils/custom_ops.py'
with open(ops_file, 'r') as f: lines = f.readlines()
with open(ops_file, 'w') as f:
    for line in lines:
        if "def get_plugin" in line:
            f.write(line)
            f.write("    return None # FORCE DISABLE C++ KERNELS\n")
        else:
            f.write(line)

print("✅ Install Complete.")


project_path = "/content/drive/MyDrive/Medical_GAN_Project"
runs_dir = f"{project_path}/training_runs"
dataset_zip = f"{project_path}/tbx11k_512.zip"


all_pickles = glob.glob(f"{runs_dir}/**/*.pkl", recursive=True)
my_pickles = [p for p in all_pickles if "ffhq" not in os.path.basename(p)]

if not my_pickles:
    print("⚠️ WARNING: No custom training checkpoints found yet.")
    print("   This might happen if you stopped before 'Tick 0' finished yesterday.")
    print("   We will restart using the Day 1 settings as a fallback.")
    latest_pkl = "ffhq512"
else:

    latest_pkl = max(my_pickles, key=os.path.getmtime)
    print(f"🔄 Found checkpoint from yesterday: {os.path.basename(latest_pkl)}")
    print(f"   Full Path: {latest_pkl}")

# 3. Resume Training
print("\n🚀 Resuming Training...")


#cmd = f"/content/stylegan2-ada-pytorch/train.py --outdir={runs_dir} --data={dataset_zip} --gpus=1 --metrics=none --cfg=auto --kimg=5000 --snap=3 --resume='{latest_pkl}'"
cmd = f"/content/stylegan2-ada-pytorch/train.py --outdir={runs_dir} --data={dataset_zip} --gpus=1 --metrics=none --cfg=auto --kimg=5000 --snap=1 --resume='{latest_pkl}'"
!python {cmd}















import os

print("🛑 Stopping the spam...")


ops_file = '/content/stylegan2-ada-pytorch/torch_utils/custom_ops.py'

if os.path.exists(ops_file):
    with open(ops_file, 'r') as f:
        lines = f.readlines()

    with open(ops_file, 'w') as f:
        for line in lines:
            if "def get_plugin" in line:
                f.write(line)
                # This line forces it to give up immediately, stopping the "Failed!" print
                f.write("    return None # FORCE SILENT FALLBACK\n")
            else:
                f.write(line)
    print("✅ Logic patched. The logs will be clean now.")
else:
    print("⚠️ Could not find custom_ops.py. Are you sure the repo is installed?")


import glob
project_path = "/content/drive/MyDrive/Medical_GAN_Project"
runs_dir = f"{project_path}/training_runs"
dataset_zip = f"{project_path}/tbx11k_512.zip"
repo_path = "/content/stylegan2-ada-pytorch"

# Find latest .pkl
all_pickles = glob.glob(f"{runs_dir}/**/*.pkl", recursive=True)
my_pickles = [p for p in all_pickles if "ffhq" not in os.path.basename(p)]

if my_pickles:
    latest_pkl = max(my_pickles, key=os.path.getmtime)
    print(f"\n🧠 Resuming with: {os.path.basename(latest_pkl)}")
    print("🚀 Running FID... (This will take ~30 mins. Be patient!)")

    # We use 'grep' to filter out any remaining warnings just in case
    !python {repo_path}/calc_metrics.py --metrics=fid50k_full --data={dataset_zip} --network='{latest_pkl}'
else:
    print("❌ No checkpoint found.")















import os
import glob
import shutil
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files


print("⬇️ Installing opensimplex...")
!pip install opensimplex


project_path = "/content/drive/MyDrive/Medical_GAN_Project"
runs_dir = f"{project_path}/training_runs"
output_folder = "/content/generated_images_for_paper"
repo_path = "/content/stylegan2-ada-pytorch"


if os.path.exists(output_folder):
    shutil.rmtree(output_folder)
os.makedirs(output_folder)


print("\n🔍 Looking for network-snapshot-000028.pkl...")
search_pattern = f"{runs_dir}/**/network-snapshot-000028.pkl"
found_pkls = glob.glob(search_pattern, recursive=True)

if not found_pkls:
    print("❌ ERROR: Could not find 'network-snapshot-000028.pkl'.")
    print("   Searching for ANY latest pkl instead...")
    all_pkls = glob.glob(f"{runs_dir}/**/*.pkl", recursive=True)
    my_pkls = [p for p in all_pkls if "ffhq" not in os.path.basename(p)]
    if my_pkls:
        target_pkl = max(my_pkls, key=os.path.getmtime)
    else:
        raise ValueError("No checkpoints found at all!")
else:
    target_pkl = found_pkls[0]

print(f"✅ Found: {target_pkl}")


truncation_psi = 0.7

print(f"\n🚀 Generating 20 high-res images (Seeds 500-520)...")
# We generate them as PNGs
cmd = f"python {repo_path}/generate.py --outdir={output_folder} --trunc={truncation_psi} --seeds=500-520 --network='{target_pkl}'"
!{cmd}


print("\n👀 Generating Preview Grid...")
images = sorted(glob.glob(f"{output_folder}/*.png"))[:8] # Show top 8

if images:
    plt.figure(figsize=(20, 10))
    for i, img_path in enumerate(images):
        plt.subplot(2, 4, i + 1)
        img = Image.open(img_path)
        plt.imshow(img)
        plt.axis("off")
        plt.title(os.path.basename(img_path))
    plt.tight_layout()
    plt.show()


    # ---------------------------------------------------------
    print("\n📦 Zipping images for download...")
    shutil.make_archive("/content/TB_Synthetic_Images", 'zip', output_folder)
    print("⬇️ Triggering Download...")
    files.download("/content/TB_Synthetic_Images.zip")
else:
    print("⚠️ Still no images found. Please check the error logs above.")





















